services:
  app:
    container_name: sbsctest
    restart : always
    build: 
      context: . 
      dockerfile: Dockerfile 
    env_file: .env 
    ports:
      - 3800:3800
    links:
      - mongodb
    depends_on:
      - mongodb 
  mongodb :
    container_name: mongodb 
    image: mongo:6.0 
    volumes:
      - mongodb-data:/data/db
    ports :
      - 27017:27017 
volumes:
  mongodb-data:

